name: Deploy Datamart and Hazelcast

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  validate-aws-credentials:
    name: Validate AWS Credentials
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: validate-aws-credentials

    outputs:
      hazelcast_ip: ${{ steps.save-outputs.outputs.hazelcast_ip }}
      datamart_ip: ${{ steps.save-outputs.outputs.datamart_ip }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Debug Terraform Output
        run: terraform output

      - name: Get Outputs from Parameter Store
        id: save-outputs
        run: |
          hazelcast_ip=$(aws ssm get-parameter --name "hazelcast_ip" --query "Parameter.Value" --output text --region us-east-1)
          datamart_ip=$(aws ssm get-parameter --name "datamart_ip" --query "Parameter.Value" --output text --region us-east-1)

          echo "hazelcast_ip=$hazelcast_ip"
          echo "datamart_ip=$datamart_ip"

          echo "hazelcast_ip=$hazelcast_ip" >> $GITHUB_ENV
          echo "datamart_ip=$datamart_ip" >> $GITHUB_ENV



  setup-datamart:
    name: Setup and Run Datamart
    runs-on: ubuntu-latest
    needs: deploy-infrastructure

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven 
        run: |
          wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
          tar -xvzf apache-maven-3.9.9-bin.tar.gz
          sudo mv apache-maven-3.9.9 /opt/maven
          echo "export M2_HOME=/opt/maven" >> $GITHUB_ENV
          echo "export PATH=/opt/maven/bin:\$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          mvn -version

      - name: Build Datamart
        run: |
          mvn clean package

      - name: Fetch Hazelcast IP
        run: |
          HAZELCAST_IP=$(aws ssm get-parameter --name "hazelcast_ip" --query "Parameter.Value" --output text --region us-east-1)
          echo "HAZELCAST_IP=$HAZELCAST_IP" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Run Datamart
        run: |
          java -jar target/datamart-1.0-SNAPSHOT.jar
        env:
          HAZELCAST_IP: ${{ env.HAZELCAST_IP }}


  cleanup:
    name: Cleanup Resources
    runs-on: ubuntu-latest
    needs: [deploy-infrastructure, setup-datamart]
    if: always()

    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Destroy Terraform Resources
        run: terraform destroy -auto-approve
