name: Deploy Datamart and Hazelcast
on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      aws_session_token:
        description: 'AWS Session Token'
        required: false
jobs:
  validate-aws-credentials:
    name: Validate AWS Credentials
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-session-token: ${{ github.event.inputs.aws_session_token }}
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: validate-aws-credentials

    outputs:
      hazelcast_ip: ${{ steps.get-hazelcast-ip.outputs.hazelcast_ip }}
      datamart_ip: ${{ steps.get-datamart-ip.outputs.datamart_ip }}
      MONGO_IP: ${{ steps.deploy-terraform.outputs.mongo_ip }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-session-token: ${{ github.event.inputs.aws_session_token }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy Terraform
        id: deploy-terraform
        run: |
          export MONGO_IP=$(aws ssm get-parameter --name "mongodb_ip" --query "Parameter.Value" --output text --region us-east-1)
          echo "MONGO_IP: $MONGO_IP"
          terraform apply -auto-approve -var="mongodb_ip=$MONGO_IP"
          echo "::set-output name=MONGO_IP::$MONGO_IP"
      
      - name: Get Hazelcast IP
        id: get-hazelcast-ip
        run: |
          hazelcast_ip=$(aws ssm get-parameter --name "hazelcast_ip" --query "Parameter.Value" --output text --region us-east-1)
          echo "::set-output name=hazelcast_ip::$hazelcast_ip"

  setup-datamart:
    name: Setup and Run Datamart
    runs-on: ubuntu-latest
    needs: [deploy-infrastructure]
    env:
          HAZELCAST_IP: ${{ needs.deploy-infrastructure.outputs.hazelcast_ip }}
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-session-token: ${{ github.event.inputs.aws_session_token }}
          aws-region: us-east-1

      - name: Run Datamart
        run: |
          echo "Running Datamart with Hazelcast IP: $HAZELCAST_IP"
          echo "Running DataMart with MongoDB IP: $MONGO_IP"
        env:
          HAZELCAST_IP: ${{ needs.deploy-infrastructure.outputs.hazelcast_ip }}
          MONGO_IP: ${{ needs.deploy-infrastructure.outputs.mongo_ip }}