name: Deploy Datamart and Hazelcast

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  deploy-hazelcast:
    name: Deploy Hazelcast and Datamart
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 3. Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.4

    # 4. Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # 5. Apply Terraform to deploy Hazelcast and Datamart instances
    - name: Terraform Apply
      id: terraform
      run: terraform apply -auto-approve

    # 6. Extract the IP of Hazelcast instance
    - name: Get Hazelcast IP
      run: |
        HAZELCAST_IP=$(terraform output -raw hazelcast_public_ip 2>/dev/null || echo "ERROR")
        echo "HAZELCAST_IP=$HAZELCAST_IP" >> $GITHUB_ENV


    # 7. Install Java and Maven
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 8. Build Datamart Jar
    - name: Build Datamart
      run: |
        cd java-demo
        mvn clean package

    # 9. Run Datamart with Hazelcast IP
    - name: Run Datamart
      run: |
        java -jar target/datamart-1.0-SNAPSHOT.jar

    # 10. Destroy Terraform Resources
    - name: Terraform Destroy
      if: always()
      run: terraform destroy -auto-approve