name: Deploy Datamart and Hazelcast

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-hazelcast-and-datamart:
    name: Deploy Hazelcast and Datamart
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 3. Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 4. Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # 5. Apply Terraform to deploy Hazelcast and Datamart instances
    - name: Terraform Apply
      id: terraform
      run: terraform apply -auto-approve

    # 6. Extract the IP of Hazelcast instance
    - name: Get and Process Hazelcast IP
      run: |
        # Extraer la IP cruda
        RAW_OUTPUT=$(terraform output -raw hazelcast_public_ip 2>/dev/null || echo "ERROR")
        
        # Imprimir la salida cruda para depuración
        echo "Raw Hazelcast Output: $RAW_OUTPUT"
        
        # Procesar la salida para obtener solo la IP antes del primer ":"
        HAZELCAST_IP=$(echo "$RAW_OUTPUT" | awk -F':' '{print $1}' | tr -d '\r')
        
        # Imprimir la IP limpia
        echo "Processed Hazelcast IP: $HAZELCAST_IP"
        
        # Validar que no haya errores
        if [ "$HAZELCAST_IP" = "ERROR" ] || [ -z "$HAZELCAST_IP" ]; then
          echo "Failed to extract a valid Hazelcast IP from Terraform output"
          exit 1
        fi
        
        # Escribir en GITHUB_OUTPUT con un formato válido
        echo "hazelcast_ip=$HAZELCAST_IP" >> $GITHUB_ENV

    # 7. Verify Hazelcast IP Output
    - name: Debug Hazelcast IP
      run: echo "Hazelcast IP is ${{ steps.get-hazelcast-ip.outputs.HAZELCAST_IP }}"

    # 8. Install Java and Maven
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 9. Build Datamart Jar
    - name: Build Datamart
      run: |
        cd java-demo
        mvn clean package

    # 10. Run Datamart with Hazelcast IP
    - name: Run Datamart
      run: |
        echo "Running Datamart with Hazelcast IP: ${{ steps.get-hazelcast-ip.outputs.HAZELCAST_IP }}"
        java -jar target/datamart-1.0-SNAPSHOT.jar --hazelcast.ip=${{ steps.get-hazelcast-ip.outputs.HAZELCAST_IP }}

    # 11. Destroy Terraform Resources
    - name: Terraform Destroy
      if: always()
      run: terraform destroy -auto-approve
